services:
  eshop:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${PROFILE}
      CART_BASE_URL: ${CART_URL}
      COUPON_BASE_URL: ${COUPON_URL}
    depends_on:
      - db
    develop:
      watch:
        - action: sync+restart
          path: src
          target: /app/src
    entrypoint: ["mvn", "spring-boot:run"]

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: